import Foundation
import Combine

struct AIConfig {
    static let apiKey = "YOUR_OPENAI_API_KEY"
}

struct AIParsedTask: Codable {
    let title: String
    let description: String?
    let dueDate: Date?
    let priority: String?
    let category: String?
}

class AIService {
    static let shared = AIService()
    
    private init() {}
    
    func parseNaturalLanguage(_ input: String) async throws -> AIParsedTask {
        // In a real implementation, you would make a request to OpenAI API here.
        // For demonstration, we simulate an AI parsing response.
        
        try await Task.sleep(nanoseconds: 1_000_000_000) // Simulate network delay
        
        // Simple heuristic parsing for demo purposes
        var title = input
        var priority: String = "Medium"
        var category: String = "General"
        var date: Date? = nil
        
        if input.lowercased().contains("urgent") || input.lowercased().contains("asap") {
            priority = "High"
        }
        
        if input.lowercased().contains("tomorrow") {
            date = Calendar.current.date(byAdding: .day, value: 1, to: Date())
        } else if input.lowercased().contains("next week") {
            date = Calendar.current.date(byAdding: .day, value: 7, to: Date())
        }
        
        if input.lowercased().contains("work") {
            category = "Work"
        } else if input.lowercased().contains("groceries") || input.lowercased().contains("buy") {
            category = "Shopping"
        }
        
        return AIParsedTask(
            title: title,
            description: "Auto-generated by AI Assistant",
            dueDate: date,
            priority: priority,
            category: category
        )
    }
    
    func suggestTasks(basedOn history: [String]) async throws -> [String] {
        // Simulate task suggestions
        try await Task.sleep(nanoseconds: 1_000_000_000)
        return [
            "Review weekly goals",
            "Clean the workspace",
            "Plan next vacation",
            "Read 30 minutes"
        ]
    }
}
